#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSwaps' function below.
#
# The function accepts INTEGER_ARRAY a as parameter.
#

def countSwaps(array):
    # Write your code here
    count = 0
    
     
    for i in range(len(array) - 1):
        for j in range(len(array) - 1 - i):
            if array[j]  > array[j+1]:
                array[j] , array[j+1] = array[j+1] , array[j]
                count+=1
    print("Array is sorted in " + str(count) + " swaps.")
    print("First Element: " + str(a[0]))
    print("Last Element: " + str(a[-1]))
    return ""


if __name__ == '__main__':
    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
